name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - run: brew install curl
    - run: brew install curlpp
    - run: brew install cmake
    - run: cd ..
    - run: git clone https://github.com/ariloc/discord-rpc-buttons.git
    - run: cd discord-rpc-buttons
    - run: mkdir build
    - run: cd build
    - run: cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local
    - run: cmake --build . --config Release --target install
    - run: cd /Users/runner/work/MacBlox
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
