name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - run: brew install curlpp
    - run: git clone https://github.com/ariloc/discord-rpc-buttons.git
    - run: |
        cd discord-rpc-buttons
        mkdir build
        sudo mkdir /usr/local/include/discord-rpc
        cd build
        sudo cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/discord-rpc
        sudo cmake --build . --config Release --target install
    - run: |
        cd ..
        cd MacBlox
        make
        make check
        make distcheck
