name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install xcode
      run: |
          xcode-select -p &> /dev/null
          if [ $? -ne 0 ]; then
            echo "[INFO] Command Line Tools for Xcode not found. Installing from softwareupdate…"
          # This temporary file prompts the 'softwareupdate' utility to list the Command Line Tools
            touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress;
            PROD=$(softwareupdate -l | grep "\*.*Command Line" | tail -n 1 | sed 's/^[^C]* //')
            softwareupdate -i "$PROD" --verbose;
          else
            echo "[INFO] Command Line Tools for Xcode have been installed."
          fi
    - name: Install brew and libs
      run: |
            NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            echo "[INFO] Install Required Libs"
            brew install wxwidgets@3.2
            brew install curlpp
            brew install cmake
            brew install curl
            brew install minizip
            brew install openssl
    - name: Install discord rpc
      run: |
            git clone https://github.com/SomeRandomGuy45/discord_rpc.git
            sudo mv ~/discord_rpc/lib/libdiscord-rpc.a /usr/local/lib
            sudo mkdir /usr/local/include/discord-rpc
            sudo mv ~/discord_rpc/include/discord_register.h /usr/local/include/discord-rpc
            sudo mv ~/discord_rpc/include/discord_rpc.h /usr/local/include/discord-rpc
    - name: Building
      run: |
        git clone https://github.com/SomeRandomGuy45/MacBlox.git
        cd MacBlox
        make
        echo "[INFO] Finshed building MacBlox"
