name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install curlpp
      run: |
        git clone https://github.com/SomeRandomGuy45/curlpp.git
        cd curlpp
        mkdir build
        cd build
        sudo cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local
        sudo cmake --build . --config Release --target install
        cd ../..

    - name: Install discord-rpc-buttons and minizip
      run: |
        git clone https://github.com/SomeRandomGuy45/mini_zip.git
        sudo mv mini_zip/lib/libminizip.1.dylib /usr/local/lib
        sudo mv mini_zip/lib/llibminizip.a /usr/local/lib
        sudo mv mini_zip/lib/libminizip.dylib /usr/local/lib
        sudo mv mini_zip/lib/pkgconfig/minizip.pc /usr/local/lib/pkgconfig
        sudo mv mini_zip/include/minizip /usr/local/include
        cd ../..
        git clone https://github.com/ariloc/discord-rpc-buttons.git
        cd discord-rpc-buttons
        mkdir build
        cd build
        sudo cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local
        sudo cmake --build . --config Release --target install
        cd ../..

    - name: Build and test MacBlox
      run: |
        sudo mkdir -p /usr/local/include/discord-rpc
        sudo mv /usr/local/include/discord_rpc.h /usr/local/include/discord-rpc/discord_rpc.h
        sudo mv /usr/local/include/discord_register.h /usr/local/include/discord-rpc/discord_register.h
        ls /usr/local/lib/
        
        make
        make check
        make distcheck
