name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - run: brew install curl curlpp cmake
    - run: git clone https://github.com/ariloc/discord-rpc-buttons.git
    - run: |
        cd discord-rpc-buttons
        mkdir build
        cd build
        sudo cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local
        sudo cmake --build . --config Release --target install
    - run: |
        cd ..
        echo "$PWD"
        make
        make check
        make distcheck
