name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Build and test MacBlox
      run: |
        sudo mkdir -p /usr/local/include/discord-rpc
        sudo mv /usr/local/include/discord_rpc.h /usr/local/include/discord-rpc/discord_rpc.h
        sudo mv /usr/local/include/discord_register.h /usr/local/include/discord-rpc/discord_register.h
        ls /usr/local/lib/
        
        make
        make check
        make distcheck
