name: Xcode - Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install certificates
        run: |
            echo "$SIGNING_CERTIFICATE" | base64 --decode > macos_development.cer
            security import macos_development.cer -k ~/Library/Keychains/login.keychain -T /usr/bin/codesign
            echo "$SIGNING_KEY" | base64 --decode > macos_development.p12
            security import macos_development.p12 -P "$SIGNING_KEY_PASSWORD" -k ~/Library/Keychains/login.keychain
            security set-key-partition-list -S apple-tool:,apple: -s -k build_password ~/Library/Keychains/login.keychain
        env:
          SIGNING_CERTIFICATE: ${{ secrets.SIGNING_CERTIFICATE }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name : Enter build dir
        run : |
            cd "Smart Join"
            echo "$PWD"

      - name: Build
        run: |
          xcodebuild -project ~/work/MacBlox/MacBlox/"Smart Join"/"Smart Join.xcodeproj" -scheme "Smart Join" -configuration Release -derivedDataPath ~/work/MacBlox/MacBlox/"Smart Join"
          echo "$PWD"