name: Xcode - Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name : Enter build dir
        run : |
            cd "Smart Join"
            echo "$PWD"
      - name: Build
        run: |
          xcodebuild -project ~/work/MacBlox/MacBlox/"Smart Join"/"Smart Join.xcodeproj" -scheme "Smart Join" -configuration Release -derivedDataPath ~/work/MacBlox/MacBlox/"Smart Join"
          echo "$PWD"
