name: Xcode - Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse default scheme using xcodebuild command
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: MacBlox  # Ensure the correct path is checked out

      - name: Install certificates
        run: |
            # (Install certificates and keychain setup steps)
            echo "$SIGNING_CERTIFICATE" | base64 --decode > macos_development.cer
            security import macos_development.cer -k ~/Library/Keychains/build.keychain-db -T /usr/bin/codesign
            echo "$SIGNING_KEY" | base64 --decode > macos_development.p12
            security import macos_development.p12 -P "$SIGNING_KEY_PASSWORD" -k ~/Library/Keychains/build.keychain-db
            security set-key-partition-list -S apple-tool:,apple: -s -k build_password ~/Library/Keychains/build.keychain-db
            rm macos_development.cer macos_development.p12

      - name: Build
        run: |
          cd ~/work/MacBlox/MacBlox/Smart\ Join  # Adjust the path if needed
          xcodebuild -project "Smart Join.xcodeproj" -scheme "Smart Join" -configuration Release -derivedDataPath ~/work/MacBlox/MacBlox/Smart\ Join